version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: market_user
      POSTGRES_PASSWORD: market_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  auth_service:
    build: ./auth_service
    env_file:
      - infra/envs/.env.common
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    networks:
      - backend

  product_service:
    build: ./product_service
    env_file:
      - infra/envs/.env.common
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    networks:
      - backend

  payment_service:
    build: ./payment_service
    env_file:
      - infra/envs/.env.common
    depends_on:
      - postgres
    ports:
      - "8083:8080"
    networks:
      - backend

  chatbot_service:
    build: ./chatbot_service
    env_file:
      - infra/envs/.env.common
    ports:
      - "8000:8000"
    networks:
      - backend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - frontend

  nginx:
    image: nginx:1.27
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - auth_service
      - product_service
      - payment_service
      - chatbot_service
    networks:
      - frontend
      - backend

networks:
  frontend: {}
  backend: {}

volumes:
  pgdata: {}
